package com.example.tddclassmanagementapp.data.source.entities;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.room.ColumnInfo;
import androidx.room.Entity;
import androidx.room.PrimaryKey;

import java.util.Objects;
import java.util.UUID;


/**
 * @see ClassRoom represents the "class_rooms" database table
 * Attributes:
 * - [id] is the autogenerated unique string primary key
 * - [name] is name of the class, typically the subject name
 * - [teacher_id] is the foreign key to teacher's primary key
 * teaching the class, it can be null, which means that a class
 * can exist without a teacher.
 */
@Entity(tableName = "class_rooms")
public class ClassRoom {
    @PrimaryKey
    @NonNull
    private String id;

    @NonNull
    private String name;

    @ColumnInfo(name = "teacher_id")
    @Nullable
    private String teacherId;

    public ClassRoom(@NonNull String name, @Nullable String teacherId) {
        this.name = name;
        this.teacherId = teacherId;
        this.id = UUID.randomUUID().toString();
    }

    @NonNull
    public String getId() {
        return id;
    }

    @NonNull
    public String getName() {
        return name;
    }

    @Nullable
    public String getTeacherId() {
        return teacherId;
    }

    public void setId(@NonNull String id) {
        this.id = id;
    }

    public void setName(@NonNull String name) {
        this.name = name;
    }

    public void setTeacherId(@Nullable String teacher_id) {
        this.teacherId = teacher_id;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        ClassRoom classRoom = (ClassRoom) o;
        return id.equals(classRoom.id) &&
                name.equals(classRoom.name) &&
                ((teacherId == null && classRoom.teacherId == null) ||
                        teacherId.equals(classRoom.teacherId));
    }

    @Override
    public String toString() {
        return "ClassRoom{" +
                "id='" + id + '\'' +
                ", name='" + name + '\'' +
                ", teacherId='" + teacherId + '\'' +
                '}';
    }
}
