package com.example.tddclassmanagementapp.data.source.entities;

import androidx.annotation.NonNull;
import androidx.room.Entity;
import androidx.room.PrimaryKey;

import java.util.UUID;

/**
 * @see Teacher represents the database table "teachers"
 * - [id] is the autogenerated string primary key
 * - [name] represents name of the Teacher
 */
@Entity(tableName = "teachers")
public class Teacher {
    @PrimaryKey
    @NonNull
    private String id;

    @NonNull
    private String name;

    /**
     * A random String token is assigned as [id]
     * @param name is name of Teacher instance
     */
    public Teacher(String name) {
        this.name = name;
        this.id = UUID.randomUUID().toString();
    }

    public String getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public void setId(@NonNull String id) {
        this.id = id;
    }

    public void setName(@NonNull String name) {
        this.name = name;
    }
}
